trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self  # Ensure the repository is checked out

- script: |
    echo "##[section]Listing files in the working directory"
    ls -R  # List all files for debugging
  displayName: 'List Files'

- task: Maven@4
  inputs:
    azureSubscription: 'Pay-As-You-Go (82c579f8-0ab8-43ec-8c87-eca2d5f2c821)'
    mavenPomFile: 'pom.xml'
    goals: 'clean test -e'  # Use -e for detailed error messages
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- script: |
    echo "##[section]Listing Surefire Reports"
    ls -R target/surefire-reports  # List the contents of the reports directory
  displayName: 'List Surefire Reports'
